package com.guiyideguang.panta.zhen.po;

import java.io.Serializable;

public class Phone implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_id
     *
     * @mbg.generated
     */
    private Integer phoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone_type
     *
     * @mbg.generated
     */
    private String phoneType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.doc_address
     *
     * @mbg.generated
     */
    private String docAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.op_address
     *
     * @mbg.generated
     */
    private String opAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.afsale_address
     *
     * @mbg.generated
     */
    private String afsaleAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_id
     *
     * @return the value of phone.phone_id
     *
     * @mbg.generated
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_id
     *
     * @param phoneId the value for phone.phone_id
     *
     * @mbg.generated
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone_type
     *
     * @return the value of phone.phone_type
     *
     * @mbg.generated
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone_type
     *
     * @param phoneType the value for phone.phone_type
     *
     * @mbg.generated
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType == null ? null : phoneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.doc_address
     *
     * @return the value of phone.doc_address
     *
     * @mbg.generated
     */
    public String getDocAddress() {
        return docAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.doc_address
     *
     * @param docAddress the value for phone.doc_address
     *
     * @mbg.generated
     */
    public void setDocAddress(String docAddress) {
        this.docAddress = docAddress == null ? null : docAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.op_address
     *
     * @return the value of phone.op_address
     *
     * @mbg.generated
     */
    public String getOpAddress() {
        return opAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.op_address
     *
     * @param opAddress the value for phone.op_address
     *
     * @mbg.generated
     */
    public void setOpAddress(String opAddress) {
        this.opAddress = opAddress == null ? null : opAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.afsale_address
     *
     * @return the value of phone.afsale_address
     *
     * @mbg.generated
     */
    public String getAfsaleAddress() {
        return afsaleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.afsale_address
     *
     * @param afsaleAddress the value for phone.afsale_address
     *
     * @mbg.generated
     */
    public void setAfsaleAddress(String afsaleAddress) {
        this.afsaleAddress = afsaleAddress == null ? null : afsaleAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneId=").append(phoneId);
        sb.append(", phoneType=").append(phoneType);
        sb.append(", docAddress=").append(docAddress);
        sb.append(", opAddress=").append(opAddress);
        sb.append(", afsaleAddress=").append(afsaleAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}