package com.guiyideguang.panta.zhen.dao;



import com.guiyideguang.panta.zhen.po.Phone;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    Phone selectByPrimaryKey(Integer phoneId);
    @Select("select doc_address from phone where phone_type = #{phonetype}  limit 1")
    String selectdocByVer(String phonetype);
    @Select("select op_address from phone where phone_type = #{phonetype}  limit 1")
    String selectopByVer(String phonetype);
    @Select("select afsale_address from phone where phone_type = #{phonetype}  limit 1")
    String selectafsaleByVer(String phonetype);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    List<Phone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Phone record);
}